env:
  global:
    - CC_TEST_REPORTER_ID=c0f63eb0066cffbb284331c1e201db4de16fdac07316ced0580f984109a1a2a3
language: go
go:
  - 1.9.x
  - 1.10.x
  - tip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -tags=integration -coverprofile=c.out -covermode=atomic
after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
services:
  - redis-server
